### PR TITLE
Icn branch

### PR DESCRIPTION
**Pull request by ICN-1**
I have made a pull request. I am happy :)

### CODE REVIEW

**Review by tsola2002 — CHANGES_REQUESTED** [review]
change the content to git class is finishing by next weeek not this week. sorry :(

**Comment by ICN-1** [comment]
I have made the changes.

**Comment by ICN-1** [comment]
I have made the changes again.

**Review by tsola2002 — APPROVED** [review]
Good Job Ife :)

**Comment by ICN-1** [comment]
I am merging this pull request now

**Pull request merged**
